### ISSUE TITLE
Issue in Jugaadu Flex Marks

### ISSUE THREAD

**Issue by mhuzaifi0604** [fahadsheikh003/Jugaadu-Flex-2.0#1]
I think there is something wrong with marks calculation in jugaadu flex, as it is showing for instance 52 out of 50 absolutes for subjects.

**Comment by asharbinkhalil** [comment]
It is technically out of scope for jugaadu to calculate maximum marks.

**Comment by fahadsheikh003** [comment]
Thank you @asharbinkhalil for clarifying and @mhuzaifi0604 as Ashar mentioned we can't calculate class average, minimum and maximum marks precisely as we don't have records of all students.
